# Niki-docAI Context Prompt
> Generated by `ndoc prompt` for AI Assistant.
> Target: {target_file}

## 1. Global Rules (Condensed)
{global_rules}

## 2. Domain Context (Nearest _AI.md)
{domain_context}

## 3. Syntax Summary
{syntax_summary}

## 4. Related APIs (Imports)
{related_apis}

{semantic_context}

## 5. Target Code
> File: {target_file}
```python
{target_code}
```
