# <NIKI_AUTO_HEADER_START>
# ------------------------------------------------------------------------------
# 🧠 Niki-docAI Context (Auto-Generated)
#
# [Local Rules] (_AI.md)
# *   **Dynamic Capability Loading**: New flows (like `capability_flow.py`) must be registered in `entry.py` to ensure ...
# *   **Auto-Provisioning**: `capability_flow` acts as the project's "immune system", proactively detecting and install...
# *   **Doctor Integration**: `doctor_flow` should reuse the `CapabilityManager` logic to verify system health, rather ...
# ------------------------------------------------------------------------------
# <NIKI_AUTO_HEADER_END>
"""
Flow: Configuration Loading.
业务流：从 _RULES.md 加载项目配置 (Documentation as Configuration).
"""
import re
from pathlib import Path
from typing import List, Set

from ndoc.models.config import ProjectConfig, ScanConfig
from ..core import io

# Default Rules Template
RULES_TEMPLATE = """# Project Rules
> @CONTEXT: Configuration | @TAGS: @CONFIG @RULES

## Scanning Rules (扫描规则)
> 定义哪些文件应该被忽略或包含。

- `!IGNORE`: .git, .vscode, .idea, __pycache__, node_modules, dist, build, .venv, venv
- `!INCLUDE`: .py, .md, .json, .js, .ts, .html, .css, .yml, .yaml, .toml

## Documentation Style (文档风格)
> 定义生成的文档样式。

- `!LANG`: Chinese (zh-CN)

## ALM & Memory Rules (ALM与记忆规则)
> 定义项目生命周期与自动归档规则。

- `MEMORY文档对齐`: 定期更新_MEMORY.md，每当_NEXT.md中一项功能/模块完成，将其归档入_MEMORY.md。
- `交付即更新`: 在完成代码修改后，习惯性运行 `ndoc all`，确保改动被即时索引。

## Quality Gates (质量门禁)
> 定义可选的质量门禁命令，使用 `;` 分隔，留空表示不启用。

- `!LINT`: 
- `!TYPECHECK`: 

## Architecture Rules (架构规则)
> 定义项目架构约束与分层规则。

- `!RULE`: `@LAYER(core) CANNOT_IMPORT @LAYER(ui)` (示例：核心层不能依赖UI层)
- `!RULE`: `@FORBID(hardcoded_paths)` (示例：禁止硬编码路径)

## Special Keywords (特殊关键字)
> 用于控制特定目录的文档生成行为。

- `@AGGREGATE`: **Recursive Aggregation**. 当目录包含此标记时，不为子目录生成单独的 `_AI.md`，而是将其内容递归聚合到父级 `_AI.md` 中。
- `@CHECK_IGNORE`: **Audit Ignore**. 当目录包含此标记时，完全跳过该目录及其子目录的 `_AI.md` 生成。
"""

# AI Guide Template
GUIDE_TEMPLATE = """# AI Context Guide (Niki-docAI)

> **Instructions for AI Assistants (Copilot, Cursor, Trae)**
> This file teaches YOU how to use the Niki-docAI toolchain to assist the user.
> **DO NOT EDIT THIS FILE**. It is auto-generated by `ndoc init`.

## 1. Core Features (基础工作流)
These are the most commonly used commands for maintaining "code-doc" synchronization.

*   `ndoc all` (**全量刷新**)
    *   **Description**: Scans the entire project and updates all metadata docs (`_AI.md`, `_MAP.md`, `_ARCH.md`, etc.).
    *   **Usage**: Run after completing a round of code changes to ensure documentation reflects the latest code state.
*   `ndoc check` (**架构检查**)
    *   **Description**: Verifies if code violates architectural layering rules defined in `_ARCH.md` or `_RULES.md` (e.g., "Client must not depend on Engine internals").
    *   **Usage**: Run before committing code (CI/CD) to prevent architectural rot.
*   `ndoc deps [path]` (**依赖分析**)
    *   **Description**: Generates a dependency graph for the specified directory or file.
    *   **Usage**: Troubleshoot circular dependencies and understand module coupling.
*   `ndoc skeleton <file>` (**API 骨架提取**)
    *   **Description**: Extracts class/function signatures (ignoring implementation) from a file.
    *   **Usage**: Quickly understand the API surface of third-party code or complex modules.

## 2. Advanced / AI Enhanced Features (智能辅助)
These features leverage Vector DB and Semantic Analysis for Niki-docAI's core differentiation.

*   `ndoc prompt <file> --focus` (**语义上下文检索**)
    *   **Description**: Uses local Vector DB (`.ndoc/vectordb`) to retrieve code snippets and docs semantically relevant to the target `<file>`.
    *   **Usage**: Provides precise Context for AI, solving the "limited context window" problem.
*   `ndoc impact` (**变更影响分析**)
    *   **Description**: Analyzes which downstream modules, tests, or docs are affected by current changes (Git Diff aware).
    *   **Usage**: Determine regression test scope after modifying low-level libraries.
*   `ndoc init` (**脚手架初始化**)
    *   **Description**: Generates `.ndoc` directory structure and basic config files (`_GUIDE.md`, `_RULES.md`) in a new project.
    *   **Usage**: Onboard an existing project into the Niki-docAI system.
*   `ndoc search <query>` (**自然语言代码搜索**) *(Coming Soon)*
    *   **Description**: Search codebase using natural language (e.g., "How is damage calculated?").
    *   **Usage**: Locate business logic implementation without memorizing exact class/function names.

## 3. Recommended API for Agents (通用接口)
If wrapping these features as an MCP Server or Agent Tool, expose the following interfaces:

1.  `refresh_context()` -> `ndoc all`
2.  `get_semantic_context(query_or_file)` -> `ndoc prompt ... --focus`
3.  `validate_architecture()` -> `ndoc check`
4.  `analyze_impact(diff)` -> `ndoc impact`
5.  `get_module_dependencies(path)` -> `ndoc deps`

## 4. How to Read Context
*   **Project Structure**: Read `_MAP.md` first to understand the file tree.
*   **Architecture**: Read `_ARCH.md` and `_DEPS.md` to understand system design.
*   **Detailed Context**: Use `ndoc prompt <file> --focus` to get relevant code context (Vector Search).

## 5. Workflow Protocol
1.  **Explore**: Start by reading `_MAP.md` and `_ARCH.md`.
2.  **Retrieve**: When User asks about a specific feature, use `ndoc prompt ... --focus`.
3.  **Implement**: Write code.
4.  **Verify**: Run `ndoc check` and `ndoc deps`.
5.  **Update**: Remind User to run `ndoc all` to update documentation.
"""

def load_project_config(root_path: Path) -> ProjectConfig:
    """
    加载项目配置 (Load Project Configuration).
    Priority: _RULES.md > Default
    """
    # 1. Initialize with Defaults
    # We start with the default ScanConfig defined in models/config.py
    # But we want to allow _RULES.md to extend/override.
    
    # Create base config
    scan_config = ScanConfig(root_path=root_path)
    config = ProjectConfig(scan=scan_config, name=root_path.name)
    
    # 2. Load from _RULES.md
    rules_file = root_path / "_RULES.md"
    
    if rules_file.exists():
        print(f"Loading configuration from {rules_file.name}...")
        _parse_rules(rules_file, config)
    else:
        print(f"No {rules_file.name} found. Using default configuration.")
        # Optional: Auto-create? Let's leave that to a separate init step or user action.
        # But for "Documentation as Configuration", maybe we should create it if missing?
        # User asked for "Documentation as Configuration" scheme.
        # Let's create it if it doesn't exist to encourage usage, similar to Syntax Flow?
        # Or maybe just let the user know.
        pass

    return config

def ensure_rules_file(root_path: Path, force: bool = False) -> bool:
    """
    确保 _RULES.md 存在 (Ensure _RULES.md exists).
    :param force: If True, overwrite existing file.
    """
    rules_file = root_path / "_RULES.md"
    if force or not rules_file.exists():
        if force:
             print(f"Restoring default Rules Configuration at {rules_file.name}...")
        else:
             print(f"Creating default Rules Configuration at {rules_file.name}...")
        return io.write_text(rules_file, RULES_TEMPLATE)
    return False

def ensure_guide_file(root_path: Path, force: bool = False) -> bool:
    """
    确保 _GUIDE.md 存在 (Ensure _GUIDE.md exists).
    This file instructs AI how to use Niki-docAI tools.
    """
    guide_file = root_path / "_GUIDE.md"
    if force or not guide_file.exists():
        if force:
             print(f"Updating AI Guide at {guide_file.name}...")
        else:
             print(f"Creating AI Guide at {guide_file.name}...")
        return io.write_text(guide_file, GUIDE_TEMPLATE)
    return False

def _parse_rules(file_path: Path, config: ProjectConfig) -> None:
    """
    解析规则文件并更新配置对象 (Parse rules file and update config).
    """
    content = io.read_text(file_path)
    if not content:
        return

    # Parsing Logic:
    # Look for list items with tags: - `!TAG`: args...
    # Support - or * bullet.
    # Support `!TAG`, **!TAG**, or !TAG.
    
    # Regex breakdown:
    # ^\s*[-*]\s*          : Line start, bullet (- or *)
    # (?:[`'\"*]{1,2})?    : Optional wrapper (`, ", ', **, *) - non-capturing
    # (![A-Z_]+)           : TAG (Group 1)
    # (?:[`'\"*]{1,2})?    : Optional wrapper close
    # \s*:\s*              : Separator
    # (.*)$                : Args (Group 2)
    pattern = re.compile(r"^\s*[-*]\s*(?:[`'\"*]{1,2})?(![A-Z_]+)(?:[`'\"*]{1,2})?\s*:\s*(.*)$", re.MULTILINE)
    
    ignore_set = set(config.scan.ignore_patterns)
    include_set = set(config.scan.extensions)
    lint_cmds: List[str] = list(config.lint_commands)
    typecheck_cmds: List[str] = list(config.typecheck_commands)
    
    found_ignore = False
    found_include = False
    found_lint = False
    found_typecheck = False

    def _parse_command_list(raw: str) -> List[str]:
        return [part.strip() for part in raw.split(";") if part.strip()]
    
    for match in pattern.finditer(content):
        tag = match.group(1)
        args_str = match.group(2).strip()
        
        # Split args by comma
        args = [a.strip().rstrip('/') for a in args_str.split(',') if a.strip()]
        
        if tag == "!IGNORE":
            if not found_ignore:
                # If user defines ignore, should we replace defaults or append?
                # Usually configuration implies "this is the list". 
                # But defaults like .git are rarely removed.
                # Let's adopt "Append/Extend" strategy if it's the first time we see it in file?
                # Or maybe "Replace" is cleaner for "Configuration".
                # Let's go with: If !IGNORE is present, we start with a clean slate (except maybe critical ones?)
                # Actually, safest is to Add to defaults. If user wants to un-ignore, that's harder.
                # Let's use Union for now.
                pass
            ignore_set.update(args)
            found_ignore = True
            
        elif tag == "!INCLUDE":
            # If user specifies extensions, usually they want ONLY these.
            if not found_include:
                 # If this is the first include tag, clear default empty (which means all)
                 # But wait, config.scan.extensions default is empty list (all).
                 pass
            include_set.update(args)
            found_include = True
        elif tag == "!LINT":
            lint_cmds = _parse_command_list(args_str)
            found_lint = True
        elif tag == "!TYPECHECK":
            typecheck_cmds = _parse_command_list(args_str)
            found_typecheck = True
            
    # Update Config
    if found_ignore:
        config.scan.ignore_patterns = sorted(list(ignore_set))
        
    if found_include:
        config.scan.extensions = sorted(list(include_set))
        
    if found_lint:
        config.lint_commands = lint_cmds
        
    if found_typecheck:
        config.typecheck_commands = typecheck_cmds
        
    # Debug info
    # print(f"  Loaded {len(config.scan.ignore_patterns)} ignore patterns")
    # print(f"  Loaded {len(config.scan.extensions)} extensions")
