"""
Flow: Tech Stack Snapshot Generation.
业务流：生成技术栈快照 (_TECH.md)。
"""
from datetime import datetime
from pathlib import Path
from ndoc.models.config import ProjectConfig
from ndoc.atoms import io, deps

def generate_tech_content(config: ProjectConfig) -> str:
    """
    生成 _TECH.md 内容 (Generate _TECH.md content).
    """
    lines = []
    
    root_path = config.scan.root_path
    
    # 1. Language Stats
    lines.append("## 1. Languages (语言分布)")
    languages = deps.detect_languages(root_path, set(config.scan.ignore_patterns))
    if not languages:
        lines.append("*   *(No recognizable code files found)*")
    else:
        for lang, pct in languages.items():
            bar_len = int(pct / 5)
            bar = "█" * bar_len + "░" * (20 - bar_len)
            lines.append(f"*   **{lang}**: `{bar}` {pct}%")
            
    lines.append("")
    
    # 2. Dependencies
    lines.append("## 2. Dependencies (依赖库)")
    all_deps = deps.get_project_dependencies(root_path)
    
    if not all_deps:
        lines.append("*   *(No dependency files detected)*")
    else:
        for source, items in all_deps.items():
            lines.append(f"### {source}")
            if not items:
                lines.append("*   *(Empty)*")
            else:
                for item in items:
                    lines.append(f"*   `{item}`")
            lines.append("")

    # 3. Environment (Placeholder)
    lines.append("## 3. Environment (开发环境)")
    lines.append("*   **OS**: Windows (Detected)")
    lines.append("*   **Python**: Detected via file extension")
    
    return "\n".join(lines)

def run(config: ProjectConfig) -> bool:
    """
    执行 Tech Flow (Execute Tech Flow).
    """
    print(f"Generating Tech Stack Snapshot...")
    
    content = generate_tech_content(config)
    
    tech_file = config.scan.root_path / "_TECH.md"
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Template
    template = f"""# Tech Stack Snapshot
> @CONTEXT: Global | _TECH.md | @TAGS: @TECH @DEPS
> 最后更新 (Last Updated): {timestamp}

{content}

---
*Generated by Niki-docAI*
"""
    
    io.write_text(tech_file, template)
    print(f"✅ Tech Snapshot updated: {tech_file.name}")
    return True
