import os
import stat
from pathlib import Path
from ndoc.core import console, utils

PRE_COMMIT_HOOK = """#!/bin/sh
# Niki-docAI Pre-commit Hook
# Auto-generated by 'ndoc hooks install'

echo "🔍 [Niki-docAI] Running pre-commit checks..."

# 1. Verify Project Rules
# If this fails, commit is aborted.
ndoc verify
if [ $? -ne 0 ]; then
    echo "❌ [Niki-docAI] Verification failed. Please fix violations."
    exit 1
fi

# 2. Update Documentation
# We attempt to update the project map and local contexts.
echo "🔄 [Niki-docAI] Syncing documentation..."
ndoc map update > /dev/null 2>&1
ndoc docs update --all > /dev/null 2>&1

# 3. Check for unstaged changes in documentation
# If ndoc updated any files, they will appear as modified but unstaged (or staged if we use git add, but we shouldn't auto-add).
# We want to stop the commit if docs changed, so the user can review and add them.

# Get list of modified files that are NOT staged for this commit, 
# but were modified by the commands above.
# Note: 'git diff --name-only' shows unstaged changes.
unstaged_docs=$(git diff --name-only | grep -E "_AI.md|_MAP.md|_ARCH.md")

if [ ! -z "$unstaged_docs" ]; then
    echo "⚠️  [Niki-docAI] Documentation updated!"
    echo "   The following files were synchronized with your code changes:"
    echo "$unstaged_docs"
    echo ""
    echo "👉 Action Required: Review these changes, 'git add' them, and commit again."
    exit 1
fi

echo "✅ [Niki-docAI] All checks passed."
exit 0
"""

def install_hooks(root: Path):
    """
    Installs git hooks into .git/hooks directory.
    """
    git_dir = root / ".git"
    if not git_dir.exists():
        console.error(f"Not a git repository: {root}")
        return False

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    
    pre_commit_path = hooks_dir / "pre-commit"
    
    # Write the hook
    try:
        console.info(f"Installing pre-commit hook to {pre_commit_path}...")
        with open(pre_commit_path, "w", encoding="utf-8", newline='\n') as f:
            f.write(PRE_COMMIT_HOOK)
            
        # Make executable (chmod +x)
        st = os.stat(pre_commit_path)
        os.chmod(pre_commit_path, st.st_mode | stat.S_IEXEC)
        
        console.success("Git hooks installed successfully!")
        console.info("Now 'ndoc verify' and auto-updates will run on every commit.")
        return True
    except Exception as e:
        console.error(f"Failed to install hooks: {e}")
        return False

def cmd_hooks(root: Path, action: str):
    if action == "install":
        install_hooks(root)
    else:
        console.error(f"Unknown hook action: {action}")