> **Instructions for AI Assistants (Copilot, Cursor, Trae)**
> This file teaches YOU how to use the Niki-docAI toolchain to assist the user.
> **DO NOT EDIT THIS FILE**. It is auto-generated by `ndoc init`.

## 1. Core Features (基础工作流)
These are the most commonly used commands for maintaining "code-doc" synchronization.

*   `ndoc all` (**全量刷新**)
    *   **Description**: Scans the entire project and updates all metadata docs (`_AI.md`, `_MAP.md`, `_ARCH.md`, etc.).
    *   **Usage**: Run after completing a round of code changes to ensure documentation reflects the latest code state.
*   `ndoc check` (**架构检查**)
    *   **Description**: Verifies if code violates architectural layering rules defined in `_ARCH.md` or `_RULES.md` (e.g., "Client must not depend on Engine internals").
    *   **Usage**: Run before committing code (CI/CD) to prevent architectural rot.
*   `ndoc deps [path]` (**依赖分析**)
    *   **Description**: Generates a dependency graph for the specified directory or file.
    *   **Usage**: Troubleshoot circular dependencies and understand module coupling.
*   `ndoc skeleton <file>` (**API 骨架提取**)
    *   **Description**: Extracts class/function signatures (ignoring implementation) from a file.
    *   **Usage**: Quickly understand the API surface of third-party code or complex modules.

## 2. Advanced / AI Enhanced Features (智能辅助)
These features leverage Vector DB and Semantic Analysis for Niki-docAI's core differentiation.

*   `ndoc prompt <file> --focus` (**语义上下文检索**)
    *   **Description**: Uses local Vector DB (`.ndoc/vectordb`) to retrieve code snippets and docs semantically relevant to the target `<file>`.
    *   **Usage**: Provides precise Context for AI, solving the "limited context window" problem.
*   `ndoc impact` (**变更影响分析**)
    *   **Description**: Analyzes which downstream modules, tests, or docs are affected by current changes (Git Diff aware).
    *   **Usage**: Determine regression test scope after modifying low-level libraries.
*   `ndoc init` (**脚手架初始化**)
    *   **Description**: Generates `.ndoc` directory structure and basic config files (`_GUIDE.md`, `_RULES.md`) in a new project.
    *   **Usage**: Onboard an existing project into the Niki-docAI system.
*   `ndoc search <query>` (**自然语言代码搜索**) *(Coming Soon)*
    *   **Description**: Search codebase using natural language (e.g., "How is damage calculated?").
    *   **Usage**: Locate business logic implementation without memorizing exact class/function names.

## 3. Recommended API for Agents (通用接口)
If wrapping these features as an MCP Server or Agent Tool, expose the following interfaces:

1.  `refresh_context()` -> `ndoc all`
2.  `get_semantic_context(query_or_file)` -> `ndoc prompt ... --focus`
3.  `validate_architecture()` -> `ndoc check`
4.  `analyze_impact(diff)` -> `ndoc impact`
5.  `get_module_dependencies(path)` -> `ndoc deps`

## 4. How to Read Context
*   **Project Structure**: Read `_MAP.md` first to understand the file tree.
*   **Architecture**: Read `_ARCH.md` and `_DEPS.md` to understand system design.
*   **Detailed Context**: Use `ndoc prompt <file> --focus` to get relevant code context (Vector Search).

## 5. Workflow Protocol
1.  **Explore**: Start by reading `_MAP.md` and `_ARCH.md`.
2.  **Retrieve**: When User asks about a specific feature, use `ndoc prompt ... --focus`.
3.  **Implement**: Write code.
4.  **Verify**: Run `ndoc check` and `ndoc deps`.
5.  **Update**: Remind User to run `ndoc all` to update documentation.
